//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.App.Common.Validation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangStringNotEmptyAttribute {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangStringNotEmptyAttribute() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.App.Common.Validation.LangStringNotEmptyAttribute", typeof(LangStringNotEmptyAttribute).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AtLeastOneValueRequired {
            get {
                return ResourceManager.GetString("AtLeastOneValueRequired", resourceCulture);
            }
        }
        
        public static string NotALangString {
            get {
                return ResourceManager.GetString("NotALangString", resourceCulture);
            }
        }
        
        public static string MissingEntriesForRequiredLanguages {
            get {
                return ResourceManager.GetString("MissingEntriesForRequiredLanguages", resourceCulture);
            }
        }
        
        public static string EmptyLanguageKey {
            get {
                return ResourceManager.GetString("EmptyLanguageKey", resourceCulture);
            }
        }
        
        public static string EmptyValues {
            get {
                return ResourceManager.GetString("EmptyValues", resourceCulture);
            }
        }
    }
}
