version: "3.9"

services:
  videoarchiver-db:
    container_name: videoarchiver-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    # external:internal
      - "5432:5432"
    volumes:
      - videoarchiver-db-postgres-volume:/var/lib/postresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

volumes:
  videoarchiver-db-postgres-volume: