version: "3.9"

services:
  db:
    container_name: db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      # external:internal
      - "5433:5432"
    volumes:
      - db-postgres-volume:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      main:
        aliases:
          - db
  webapp:
    container_name: webapp
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=User ID=postgres;Password=postgres;Host=db;Port=5432;Database=video_archiver;
    ports:
      - "8080:80"
    volumes:
      - downloads-volume:/app/downloads
    networks:
      - main

volumes:
  db-postgres-volume:
  downloads-volume:

networks:
  main: