//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.WebApp.Views.Video {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Watch {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Watch() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.WebApp.Views.Video.Watch", typeof(Watch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WatchArchived {
            get {
                return ResourceManager.GetString("WatchArchived", resourceCulture);
            }
        }
        
        public static string WatchOnPlatform {
            get {
                return ResourceManager.GetString("WatchOnPlatform", resourceCulture);
            }
        }
        
        public static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        public static string SetArchivePrivacyStatus {
            get {
                return ResourceManager.GetString("SetArchivePrivacyStatus", resourceCulture);
            }
        }
        
        public static string SetArchivePrivacyStatusSubmit {
            get {
                return ResourceManager.GetString("SetArchivePrivacyStatusSubmit", resourceCulture);
            }
        }
        
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        public static string CommentsOnPlatformCount {
            get {
                return ResourceManager.GetString("CommentsOnPlatformCount", resourceCulture);
            }
        }
        
        public static string ArchivedRootCommentsCount {
            get {
                return ResourceManager.GetString("ArchivedRootCommentsCount", resourceCulture);
            }
        }
        
        public static string ArchivedTotalCommentsCount {
            get {
                return ResourceManager.GetString("ArchivedTotalCommentsCount", resourceCulture);
            }
        }
        
        public static string LikesCount {
            get {
                return ResourceManager.GetString("LikesCount", resourceCulture);
            }
        }
        
        public static string CommentsNotYetFetched {
            get {
                return ResourceManager.GetString("CommentsNotYetFetched", resourceCulture);
            }
        }
        
        public static string CommentsLastFetched {
            get {
                return ResourceManager.GetString("CommentsLastFetched", resourceCulture);
            }
        }
    }
}
